// <auto-generated />
using System;
using MiTienda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiTienda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124063754_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiTienda.Entities.Categoria", b =>
                {
                    b.Property<int>("categoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaID"));

                    b.Property<string>("categoriaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoriaID");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            categoriaID = 1,
                            categoriaNombre = "Tecnologia"
                        },
                        new
                        {
                            categoriaID = 2,
                            categoriaNombre = "Bedroom"
                        });
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.Property<int>("ordenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ordenID"));

                    b.Property<DateTime>("ordenFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ordenTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("usuarioID")
                        .HasColumnType("int");

                    b.HasKey("ordenID");

                    b.HasIndex("usuarioID");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("MiTienda.Entities.OrdenItem", b =>
                {
                    b.Property<int>("ordenItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ordenItemID"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ordenID")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("productoID")
                        .HasColumnType("int");

                    b.HasKey("ordenItemID");

                    b.HasIndex("ordenID");

                    b.HasIndex("productoID");

                    b.ToTable("OrdenItem");
                });

            modelBuilder.Entity("MiTienda.Entities.Producto", b =>
                {
                    b.Property<int>("productoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productoID"));

                    b.Property<int>("productoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("productoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productoImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("productoPrecio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("productoStock")
                        .HasColumnType("int");

                    b.HasKey("productoID");

                    b.HasIndex("productoCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MiTienda.Entities.Usuario", b =>
                {
                    b.Property<int>("usuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuarioID"));

                    b.Property<string>("usuarioContraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ususarioTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.HasOne("MiTienda.Entities.Usuario", "ordenUsuario")
                        .WithMany("usuarioOrdenes")
                        .HasForeignKey("usuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ordenUsuario");
                });

            modelBuilder.Entity("MiTienda.Entities.OrdenItem", b =>
                {
                    b.HasOne("MiTienda.Entities.Orden", "Orden")
                        .WithMany("ordenItems")
                        .HasForeignKey("ordenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("productoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MiTienda.Entities.Producto", b =>
                {
                    b.HasOne("MiTienda.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("productoCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MiTienda.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.Navigation("ordenItems");
                });

            modelBuilder.Entity("MiTienda.Entities.Usuario", b =>
                {
                    b.Navigation("usuarioOrdenes");
                });
#pragma warning restore 612, 618
        }
    }
}
