// <auto-generated />
using System;
using MiTienda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiTienda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiTienda.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            CategoriaNombre = "Tecnologia"
                        },
                        new
                        {
                            CategoriaID = 2,
                            CategoriaNombre = "Bedroom"
                        });
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.Property<int>("OrdenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenID"));

                    b.Property<DateTime>("OrdenFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrdenTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("OrdenID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("MiTienda.Entities.OrdenItem", b =>
                {
                    b.Property<int>("OrdenItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenItemID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.HasKey("OrdenItemID");

                    b.HasIndex("OrdenID");

                    b.HasIndex("ProductoID");

                    b.ToTable("OrdenItem");
                });

            modelBuilder.Entity("MiTienda.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<int>("ProductoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ProductoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductoPrecio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoStock")
                        .HasColumnType("int");

                    b.HasKey("ProductoID");

                    b.HasIndex("ProductoCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MiTienda.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("UsuarioContraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.HasOne("MiTienda.Entities.Usuario", "OrdenUsuario")
                        .WithMany("UsuarioOrdenes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenUsuario");
                });

            modelBuilder.Entity("MiTienda.Entities.OrdenItem", b =>
                {
                    b.HasOne("MiTienda.Entities.Orden", "Orden")
                        .WithMany("OrdenItems")
                        .HasForeignKey("OrdenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MiTienda.Entities.Producto", b =>
                {
                    b.HasOne("MiTienda.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("ProductoCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MiTienda.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MiTienda.Entities.Orden", b =>
                {
                    b.Navigation("OrdenItems");
                });

            modelBuilder.Entity("MiTienda.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioOrdenes");
                });
#pragma warning restore 612, 618
        }
    }
}
